# ---------- Etapa 1: compilar Angular ----------
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# ---------- Etapa 2: servir con Nginx ----------
FROM nginx:alpine
COPY --from=build /app/dist/CareMe/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
